[package]
name = "wasm-faas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0"
wasmtime = "*"
wasmtime-wasi = "*"
wasi-common = "*"
once_cell="*"

